# Phase 2: Data Understanding

## Phase 2.1: What data have been provided?

### 2.1.1) Load and Inspect Data


Mounting Google Drive in Notebook

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Importing pandas library and Loading "Bake Sale with Profit Per Item" data saved in previous excercise

In [2]:
#import pandas
import pandas as pd

#save filepath
file_path = "/content/drive/MyDrive/Coding_Dojo_Data_Science_Excercises/02_Pandas_for_Data_Manipulation/data/ames-housing-dojo.csv"

# load in the data as a pandas dataframe
df = pd.read_csv(file_path)

Checking if dataframe loaded correctly

In [3]:
df.head()

,Unnamed: 0,PID,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Utilities,Neighborhood,Bldg Type,...,Garage Type,Garage Yr Blt,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Fence,Date Sold,SalePrice
0,0,907227090,RL,60,7200,Pave,NaN,AllPub,CollgCr,1Fam,...,Detchd,1977.0,1.0,297.0,TA,TA,Y,MnPrv,03-2006,119900.0
1,1,527108010,RL,134,19378,Pave,NaN,AllPub,Gilbert,1Fam,...,Attchd,2006.0,2.0,576.0,TA,TA,Y,NaN,03-2006,320000.0
2,2,534275170,RL,-1,12772,Pave,NaN,AllPub,NAmes,1Fam,...,Attchd,1960.0,1.0,301.0,TA,TA,Y,NaN,04-2007,151500.0
3,3,528104050,RL,114,14803,Pave,NaN,AllPub,NridgHt,1Fam,...,Attchd,2007.0,3.0,1220.0,TA,TA,Y,NaN,06-2008,385000.0
4,4,533206070,FV,32,3784,Pave,Pave,AllPub,Somerst,TwnhsE,...,Attchd,2006.0,2.0,476.0,TA,TA,Y,NaN,02-2007,193800.0

### 2.1.2) Checking and Changing Panda's Options (max_columns)


To get default max_columns we can check Panda's Options using `pd.get_option('<option>')`

In [4]:
# Demo: Finding the Current Max Cols
pd.get_option('display.max_columns')

20

By default max columns to show is 20. For changing that option we can use `pd.set_option('<option>', '<value>')`

In [8]:
# Setting the max_columns to 50
pd.set_option('display.max_columns', 50)

,Unnamed: 0,PID,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Utilities,Neighborhood,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Bsmt Unf SF,Total Bsmt SF,Central Air,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom,Kitchen,TotRms AbvGrd,Garage Type,Garage Yr Blt,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Fence,Date Sold,SalePrice
0,0,907227090,RL,60,7200,Pave,NaN,AllPub,CollgCr,1Fam,1Story,5,8,1972,1972,TA,TA,427.0,864.0,Y,864sqft,0.0,0.0,1,0,3,1,5,Detchd,1977.0,1.0,297.0,TA,TA,Y,MnPrv,03-2006,119900.0
1,1,527108010,RL,134,19378,Pave,NaN,AllPub,Gilbert,1Fam,2Story,7,5,2005,2006,Gd,TA,1335.0,1392.0,Y,2462sqft,1.0,0.0,2,1,4,1,9,Attchd,2006.0,2.0,576.0,TA,TA,Y,NaN,03-2006,320000.0
2,2,534275170,RL,-1,12772,Pave,NaN,AllPub,NAmes,1Fam,1Story,6,8,1960,1998,TA,Gd,460.0,958.0,Y,958sqft,0.0,0.0,1,0,2,1,5,Attchd,1960.0,1.0,301.0,TA,TA,Y,NaN,04-2007,151500.0
3,3,528104050,RL,114,14803,Pave,NaN,AllPub,NridgHt,1Fam,1Story,10,5,2007,2008,Ex,TA,442.0,2078.0,Y,2084sqft,1.0,0.0,2,0,2,1,7,Attchd,2007.0,3.0,1220.0,TA,TA,Y,NaN,06-2008,385000.0
4,4,533206070,FV,32,3784,Pave,Pave,AllPub,Somerst,TwnhsE,1Story,8,5,2006,2007,Gd,TA,1451.0,1511.0,Y,1565sqft,1.0,0.0,2,0,2,1,5,Attchd,2006.0,2.0,476.0,TA,TA,Y,NaN,02-2007,193800.0

Checking results with updated option

In [9]:
# Checking first 5 rows
df.head()

,Unnamed: 0,PID,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Utilities,Neighborhood,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Bsmt Unf SF,Total Bsmt SF,Central Air,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom,Kitchen,TotRms AbvGrd,Garage Type,Garage Yr Blt,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Fence,Date Sold,SalePrice
0,0,907227090,RL,60,7200,Pave,NaN,AllPub,CollgCr,1Fam,1Story,5,8,1972,1972,TA,TA,427.0,864.0,Y,864sqft,0.0,0.0,1,0,3,1,5,Detchd,1977.0,1.0,297.0,TA,TA,Y,MnPrv,03-2006,119900.0
1,1,527108010,RL,134,19378,Pave,NaN,AllPub,Gilbert,1Fam,2Story,7,5,2005,2006,Gd,TA,1335.0,1392.0,Y,2462sqft,1.0,0.0,2,1,4,1,9,Attchd,2006.0,2.0,576.0,TA,TA,Y,NaN,03-2006,320000.0
2,2,534275170,RL,-1,12772,Pave,NaN,AllPub,NAmes,1Fam,1Story,6,8,1960,1998,TA,Gd,460.0,958.0,Y,958sqft,0.0,0.0,1,0,2,1,5,Attchd,1960.0,1.0,301.0,TA,TA,Y,NaN,04-2007,151500.0
3,3,528104050,RL,114,14803,Pave,NaN,AllPub,NridgHt,1Fam,1Story,10,5,2007,2008,Ex,TA,442.0,2078.0,Y,2084sqft,1.0,0.0,2,0,2,1,7,Attchd,2007.0,3.0,1220.0,TA,TA,Y,NaN,06-2008,385000.0
4,4,533206070,FV,32,3784,Pave,Pave,AllPub,Somerst,TwnhsE,1Story,8,5,2006,2007,Gd,TA,1451.0,1511.0,Y,1565sqft,1.0,0.0,2,0,2,1,5,Attchd,2006.0,2.0,476.0,TA,TA,Y,NaN,02-2007,193800.0

In [11]:
# Checking last 10 rows
df.tail(10)

,Unnamed: 0,PID,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Utilities,Neighborhood,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Exter Qual,Exter Cond,Bsmt Unf SF,Total Bsmt SF,Central Air,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom,Kitchen,TotRms AbvGrd,Garage Type,Garage Yr Blt,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Fence,Date Sold,SalePrice
2949,2949,528228280,RL,43,3087,Pave,NaN,AllPub,Blmngtn,TwnhsE,1Story,7,5,2006,2006,Gd,TA,767.0,1220.0,Y,1364sqft,1.0,0.0,2,0,2,1,6,Attchd,2006.0,2.0,437.0,TA,TA,Y,NaN,11-2006,210250.0
2950,2950,528112010,RL,108,12228,Pave,NaN,AllPub,NridgHt,1Fam,1Story,7,5,2006,2006,Gd,TA,1721.0,1721.0,Y,1740sqft,0.0,0.0,2,0,4,1,8,Attchd,2006.0,3.0,874.0,TA,TA,Y,NaN,09-2006,293000.0
2951,2951,535377090,RL,64,6979,Pave,NaN,AllPub,OldTown,Duplex,SFoyer,6,5,1980,1980,TA,TA,0.0,1056.0,Y,1056sqft,2.0,0.0,0,0,0,2,4,Detchd,1980.0,2.0,576.0,TA,TA,Y,GdPrv,06-2010,144000.0
2952,2952,908102040,RL,67,8777,Pave,NaN,AllPub,Edwards,Duplex,1.5Fin,5,7,1900,2003,TA,TA,188.0,1272.0,Y,2200sqft,2.0,0.0,2,2,4,2,9,NaN,NaN,0.0,0.0,NaN,NaN,N,GdPrv,09-2008,145900.0
2953,2953,535150300,RL,174,25419,Pave,NaN,AllPub,NAmes,1Fam,2Story,8,4,1918,1990,Gd,Gd,140.0,1360.0,Y,3112sqft,1.0,1.0,2,0,4,1,8,Detchd,1918.0,2.0,795.0,TA,TA,Y,GdPrv,03-2006,235000.0
2954,2954,903400030,RL,50,11672,Pave,Pave,AllPub,BrkSide,1Fam,1Story,5,5,1925,1950,TA,TA,816.0,816.0,Y,816sqft,0.0,0.0,1,0,2,1,4,Detchd,1925.0,1.0,210.0,Fa,Fa,N,NaN,07-2006,109000.0
2955,2955,533234020,FV,79,10646,Pave,NaN,AllPub,Somerst,1Fam,2Story,7,5,2001,2001,TA,TA,177.0,858.0,Y,1789sqft,1.0,0.0,2,1,3,1,7,Attchd,2001.0,2.0,546.0,TA,TA,Y,NaN,06-2008,223000.0
2956,2956,908188140,RM,24,2522,Pave,NaN,AllPub,Edwards,Twnhs,2Story,7,5,2004,2004,Gd,TA,970.0,970.0,Y,1709sqft,0.0,0.0,2,0,3,1,7,Detchd,2004.0,2.0,380.0,TA,TA,Y,NaN,04-2006,137500.0
2957,2957,909254050,RL,54,7609,Pave,NaN,AllPub,Crawfor,1Fam,2Story,8,9,1925,1997,Gd,Gd,392.0,798.0,Y,1512sqft,1.0,0.0,2,0,3,1,7,Detchd,1925.0,1.0,180.0,TA,TA,P,GdPrv,06-2008,231000.0
2958,2958,902201120,RM,50,6000,Pave,NaN,AllPub,OldTown,1Fam,1Story,5,5,1948,1950,TA,TA,516.0,789.0,Y,789sqft,0.0,0.0,1,0,2,1,5,Detchd,1948.0,1.0,250.0,TA,TA,Y,NaN,04-2008,2000000.0

## Phase 2.2) What information is included in the data?

### 2.2.1) How many rows and columns?

*Rows* can be referred also as *records* or *observations*

In [13]:
# How many rows?
len(df)

2959

`df.head()` shows the number of columns. How to verify that?

In [14]:
# How many columns?
len(df.columns)

38

To get rows and columns both at once -> `df.shape`

In [16]:
# Can get both once from shape (row, col)
df.shape

(2959, 38)

### 2.2.2) What are the data types?

To get the datatype of each column we can use `df.dtypes`

In [17]:
# Find datatypes of each column
df.dtypes

Unnamed: 0          int64
PID                 int64
MS Zoning          object
Lot Frontage        int64
Lot Area            int64
Street             object
Alley              object
Utilities          object
Neighborhood       object
Bldg Type          object
House Style        object
Overall Qual        int64
Overall Cond        int64
Year Built          int64
Year Remod/Add      int64
Exter Qual         object
Exter Cond         object
Bsmt Unf SF       float64
Total Bsmt SF     float64
Central Air        object
Gr Liv Area        object
Bsmt Full Bath    float64
Bsmt Half Bath    float64
Full Bath           int64
Half Bath          object
Bedroom             int64
Kitchen             int64
TotRms AbvGrd       int64
Garage Type        object
Garage Yr Blt     float64
Garage Cars       float64
Garage Area       float64
Garage Qual        object
Garage Cond        object
Paved Drive        object
Fence              object
Date Sold          object
SalePrice         float64
dtype: object

To get a general overview of dataframe (including # of rows and rows, datatypes, etc) -> `df.info()`

In [18]:
# Check the info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2959 entries, 0 to 2958
Data columns (total 38 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      2959 non-null   int64
 1   PID             2959 non-null   int64
 2   MS Zoning       2959 non-null   object
 3   Lot Frontage    2959 non-null   int64
 4   Lot Area        2959 non-null   int64
 5   Street          2959 non-null   object
 6   Alley           201 non-null    object
 7   Utilities       2959 non-null   object
 8   Neighborhood    2959 non-null   object
 9   Bldg Type       2959 non-null   object
 10  House Style     2959 non-null   object
 11  Overall Qual    2959 non-null   int64
 12  Overall Cond    2959 non-null   int64
 13  Year Built      2959 non-null   int64
 14  Year Remod/Add  2959 non-null   int64
 15  Exter Qual      2959 non-null   object
 16  Exter Cond      2959 non-null   object
 17  Bsmt Unf SF     2958 non-null   float64
 18  Total Bsmt SF   2958 non-null   float64
 19  Central Air     2959 non-null   object
 20  Gr Liv Area     2959 non-null   object
 21  Bsmt Full Bath  2957 non-null   float64
 22  Bsmt Half Bath  2957 non-null   float64
 23  Full Bath       2959 non-null   int64
 24  Half Bath       2959 non-null   object
 25  Bedroom         2959 non-null   int64
 26  Kitchen         2959 non-null   int64
 27  TotRms AbvGrd   2959 non-null   int64
 28  Garage Type     2802 non-null   object
 29  Garage Yr Blt   2800 non-null   float64
 30  Garage Cars     2958 non-null   float64
 31  Garage Area     2958 non-null   float64
 32  Garage Qual     2800 non-null   object
 33  Garage Cond     2800 non-null   object
 34  Paved Drive     2959 non-null   object
 35  Fence           574 non-null    object
 36  Date Sold       2959 non-null   object
 37  SalePrice       2937 non-null   float64
dtypes: float64(8), int64(12), object(18)
memory usage: 878.6+ KB

### 2.2.3) Changing a data type

Now lets sort the Column 'Cumulative Quantity (Day 4)'. `sort_values()` method will sort from low to high, and `sort_values(ascending = False)` from high to low

In [ ]:
# Sort the cumulative values from low to high
df['Cumulative Quantity (Day 4)'].sort_values()

Item
cake                      3
apple pie                 5
key lime pie              6
muffin                   11
torte                    19
scone                    28
banana bread             36
rice krispies treats     40
cupcake                  48
fudge                    64
brownie                  86
cookie                  148
Name: Cumulative Quantity (Day 4), dtype: int64

In [ ]:
# Sort the cumulative values from high to low
df['Cumulative Quantity (Day 4)'].sort_values(ascending=False)

Item
cookie                  148
brownie                  86
fudge                    64
cupcake                  48
rice krispies treats     40
banana bread             36
scone                    28
torte                    19
muffin                   11
key lime pie              6
apple pie                 5
cake                      3
Name: Cumulative Quantity (Day 4), dtype: int64

If we want to get which item was the most profitable in the whole seeling, first we calculate the profite for each item adding a new column and then sort the results based in that column in descending order

In [ ]:
# Multiply two cumulative quantity by profit per item to get cumulative profit
df['Cumulative Profit (Day 4)'] = df['Cumulative Quantity (Day 4)']  * df['Profit per Item']
df

,Student,Packaging,Price,Expense,Profit per Item,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4),Cumulative Quantity (Day 4),Cumulative Profit (Day 4)
Item,,,,,,,,,,,
brownie,Hugo,Individually Wrapped (Plastic),2.25,0.25,2.00,17,19,25,25,86,172.00
cookie,Sally,Individually Wrapped (Plastic),1.25,0.50,0.75,40,32,38,38,148,111.00
cake,Martina,Boxed (Clear Plastic),9.50,5.00,4.50,1,2,0,0,3,13.50
cupcake,Joe,Boxed (Cardboard),3.50,0.75,2.75,10,14,12,12,48,132.00
fudge,Hugo,Individually Wrapped (Foil),3.00,1.00,2.00,0,20,22,22,64,128.00
banana bread,Mark,Individually Wrapped (Foil),2.75,0.50,2.25,0,10,13,13,36,81.00
torte,Jade,Boxed (Clear Plastic),10.50,5.50,5.00,0,5,7,7,19,95.00
scone,Jade,Individually Wrapped (Plastic),2.00,1.25,0.75,0,8,10,10,28,21.00
muffin,Anne,Individually Wrapped (Foil),1.50,0.75,0.75,0,3,4,4,11,8.25
rice krispies treats,Martina,Individually Wrapped (Plastic),1.25,0.25,1.00,0,0,10,30,40,40.00
apple pie,Sally,Box (Cardboard),10.00,4.00,6.00,0,0,2,3,5,30.00
key lime pie,Martina,Box (Cardboard),9.50,4.50,5.00,0,0,3,3,6,30.00

In [ ]:
# Sort to find the most profitable item
df['Cumulative Profit (Day 4)'].sort_values(ascending=False)

Item
brownie                 172.00
cupcake                 132.00
fudge                   128.00
cookie                  111.00
torte                    95.00
banana bread             81.00
rice krispies treats     40.00
apple pie                30.00
key lime pie             30.00
scone                    21.00
cake                     13.50
muffin                    8.25
Name: Cumulative Profit (Day 4), dtype: float64

## IV) Using group_by method

`group_by()` is other type of method that allows to calulated aggregations grouped by one ore more columns

Lets first group data by student using `sum()` aggregation method

In [ ]:
# groupby needs an aggregation functon
student_sums = df.groupby("Student").sum()
student_sums

<ipython-input-37-c8341bb54fb0>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  student_sums = df.groupby("Student").sum()

,Price,Expense,Profit per Item,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4),Cumulative Quantity (Day 4),Cumulative Profit (Day 4)
Student,,,,,,,,,
Anne,1.50,0.75,0.75,0,3,4,4,11,8.25
Hugo,5.25,1.25,4.00,17,39,47,47,150,300.00
Jade,12.50,6.75,5.75,0,13,17,17,47,116.00
Joe,3.50,0.75,2.75,10,14,12,12,48,132.00
Mark,2.75,0.50,2.25,0,10,13,13,36,81.00
Martina,20.25,9.75,10.50,1,2,13,33,49,83.50
Sally,11.25,4.50,6.75,40,32,40,41,153,141.00

We are interested in last column ('Cumulative Profit (Day 4)), so before using `sum()` aggregation method we can slice out that column

In [ ]:
# Obtain cumulative profit grouped by student
profit_by_student = df.groupby('Student')['Cumulative Profit (Day 4)'].sum()
# Sort from highest to lowest
profit_by_student.sort_values(ascending=False)

Student
Hugo       300.00
Sally      141.00
Joe        132.00
Jade       116.00
Martina     83.50
Mark        81.00
Anne         8.25
Name: Cumulative Profit (Day 4), dtype: float64

Lastly we can calcultate the total profit made by the club getting the sum of gthe previes Series obtained

In [ ]:
profit_by_student.sum()

861.75